name: material_action_sheet
description: A material action sheet.
version: 0.0.1
homepage: https://github.com/viral-sangani/material_action_sheet

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
